os:
  - osx
  - linux
before_install:
  - mozroots --import --sync
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export JAVA_HOME="/usr/lib/jvm/java-8-oracle"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install Caskroom/cask/java; fi

addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.bintray.com/gauge/gauge-deb nightly main'
    packages:
      - oracle-java8-set-default
      - maven
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated maven || brew upgrade maven; fi
  - mvn -version
  - ./install_latest_gauge_nightly.sh
  # use nightly once html-report is stable
  # - echo "gauge_repository_url = https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/" >> $HOME/.gauge/config/gauge.properties
language: csharp
cache:
  directories:
  - $HOME/.m2
script:
  - ./build.sh BuildInstallFT