os:
  - osx
  - linux
before_install:
  - mozroots --import --sync
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export JAVA_HOME="/usr/lib/jvm/java-8-oracle"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install Caskroom/cask/java; fi
addons:
  apt:
    sources:
      - sourceline: 'ppa:longsleep/golang-backports'
    packages:
      - oracle-java8-set-default
      - maven
      - golang-go
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated maven || brew upgrade maven; fi
  - mvn -version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated golang || brew upgrade golang; fi
  - mkdir GoWorkspace
  - export GOPATH=$(cd $GoWorkspace ; pwd)
  - go get -u -d github.com/getgauge/gauge
  - (cd $GOPATH/src/github.com/getgauge/gauge && echo "gauge_repository_url = https://raw.githubusercontent.com/getgauge/gauge-nightly-repository/master/" >> skel/gauge.properties && exec go run build/make.go)
  - (cd $GOPATH/src/github.com/getgauge/gauge && exec go run build/make.go --install)
language: csharp
cache:
  directories:
  - $HOME/.m2
script:
  - ./build.sh BuildInstallFT